name: taskapp
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  http: ^1.6.0
  shared_preferences: ^2.0.0
  image_picker: ^1.1.1
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  api_service_helper: ^1.0.0
  dio: ^5.9.0
  get_it: ^9.1.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
